apiVersion: v1
kind: ConfigMap
metadata:
  creationTimestamp: null
  name: literal-config
  namespace: default
data:
  name: dave
  password: pass
---
apiVersion: v1
kind: ConfigMap
metadata:
  creationTimestamp: null
  name: env-config
  namespace: default
data:
  log_level: INFO
---
apiVersion: v1
kind: Pod
metadata:
  name: cm-env-test-pod
  namespace: default
spec:
  containers:
  - name: test-container
    image: wangyanglinux/myapp:v1.0
    imagePullPolicy: IfNotPresent
    command: ["/bin/sh", "-c", "env"]
    env:
      - name: USERNAME
        valueFrom:
          configMapKeyRef:
            name: literal-config
            key: name
      - name: PASSWORD
        valueFrom:
          configMapKeyRef:
            name: literal-config
            key: password
    envFrom:
      - configMapRef:
          name: env-config
  restartPolicy: Never        
