apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: redis-server
  name: redis-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: redis-server
  template:
    metadata:
      labels:
        app: redis-server
    spec:
      containers:
      - image: docker.io/library/redis
        imagePullPolicy: IfNotPresent
        name: redis-server
        resources: {}
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      