apiVersion: batch/v1
kind: Job
metadata:
  name: rand
spec:
  completions: 10
  parallelism: 5
  template:
    metadata:
      name: rand
    spec:
        containers:
        - name: rand
          image: wangyanglinux/tools:randexitv1
          imagePullPolicy: IfNotPresent
        restartPolicy: Never
