apiVersion: v1
kind: Service
metadata:
  labels:
    app: myapp-test
  namespace: default
  name: myapp-test-{{now | date "20060102030405"}}-svc
spec:
  type: {{ .Values.service.type | quote}}
  selector:
    app: myapp-test
  ports:
  - name: 80-80
    port: 80
    targetPort: 80
    {{- if eq .Values.service.type "NodePort"}}
    nodePort: {{ .Values.service.nodeport }}
    {{- end}}