apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: default
  name: myapp-clusterip-deploy
spec:
  replicas: 3
  selector:
    matchLabels:
      app: myapp
      release: stabel
      svc: clusterip
  template:
    metadata:
      labels:
        app: myapp
        release: stabel
        svc: clusterip
        env: test
    spec:
      containers:
      - name: myapp-container
        image: wangyanglinux/myapp:v1.0
        imagePullPolicy: IfNotPresent
        ports:
        - name: http
          containerPort: 80
        readinessProbe:
          httpGet:
            port: 80
            path: /index1.html
          initialDelaySeconds: 1
          periodSeconds: 3  
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: myapp-clusterip
  name: myapp-clusterip
spec:
  type: ClusterIP
  selector:
    app: myapp
    release: stabel
    svc: clusterip  
  ports:
  - name: http
    port: 80
    targetPort: 80
