apiVersion: v1
kind: Service
metadata:
  name: nginx-noselectt
spec:
  ports:
  - protocol: TCP
    port: 6666
    targetPort: 80
---
apiVersion: v1
kind: Endpoints
metadata:
  name: nginx
subsets:
- addresses:
    - ip: 10.244.2.205
  ports:
    - port: 80