apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: default
  name: myapp-nodeport-deploy
spec:
  replicas: 3
  selector:
    matchLabels:
      app: myapp
      release: stabel
      svc: nodeport
  template:
    metadata:
      labels:
        app: myapp
        release: stabel
        svc: nodeport
        env: test
    spec:
      containers:
      - name: myapp-container
        image: wangyanglinux/myapp:v1.0
        imagePullPolicy: IfNotPresent
        ports:
        - name: http
          containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  namespace: default
  name: myapp-nodeport
spec:
  type: NodePort
  selector:
    app: myapp
    release: stabel
    svc: nodeport  
  ports:
  - name: http
    port: 80
    targetPort: 80
    nodePort: 30010
